version: '3'

services:
  mailserver:
    image: analogic/poste.io  # Usa la imagen oficial de Poste.io
    container_name: poste
    hostname: mail.example.com  # Cambia a tu propio hostname
    restart: always
    ports:
      - "25:25"        # SMTP
      - "465:465"      # SMTPS
      - "587:587"      # SMTP Submission
      - "110:110"      # POP3
      - "995:995"      # POP3S
      - "143:143"      # IMAP
      - "993:993"      # IMAPS
      - "80:80"        # HTTP (para interfaz de administración)
      - "443:443"      # HTTPS (para interfaz de administración)
    environment:
      - POSTE_IO_DOMAIN=example.com  # Cambia a tu propio dominio
      - POSTE_IO_HOSTNAME=mail.example.com  # Cambia a tu propio hostname
    volumes:
      - ./mail-data:/data  # Directorio de persistencia en el host
